#include "sdleventprovider.h"

#include <SDL2/SDL.h>

namespace {
e172::Scancode scancodeFromSDL(SDL_Scancode s)
{
    switch (s) {
    case SDL_SCANCODE_UNKNOWN:
        return e172::ScancodeUnknown;
    case SDL_SCANCODE_A:
        return e172::ScancodeA;
    case SDL_SCANCODE_B:
        return e172::ScancodeB;
    case SDL_SCANCODE_C:
        return e172::ScancodeC;
    case SDL_SCANCODE_D:
        return e172::ScancodeD;
    case SDL_SCANCODE_E:
        return e172::ScancodeE;
    case SDL_SCANCODE_F:
        return e172::ScancodeF;
    case SDL_SCANCODE_G:
        return e172::ScancodeG;
    case SDL_SCANCODE_H:
        return e172::ScancodeH;
    case SDL_SCANCODE_I:
        return e172::ScancodeI;
    case SDL_SCANCODE_J:
        return e172::ScancodeJ;
    case SDL_SCANCODE_K:
        return e172::ScancodeK;
    case SDL_SCANCODE_L:
        return e172::ScancodeL;
    case SDL_SCANCODE_M:
        return e172::ScancodeM;
    case SDL_SCANCODE_N:
        return e172::ScancodeN;
    case SDL_SCANCODE_O:
        return e172::ScancodeO;
    case SDL_SCANCODE_P:
        return e172::ScancodeP;
    case SDL_SCANCODE_Q:
        return e172::ScancodeQ;
    case SDL_SCANCODE_R:
        return e172::ScancodeR;
    case SDL_SCANCODE_S:
        return e172::ScancodeS;
    case SDL_SCANCODE_T:
        return e172::ScancodeT;
    case SDL_SCANCODE_U:
        return e172::ScancodeU;
    case SDL_SCANCODE_V:
        return e172::ScancodeV;
    case SDL_SCANCODE_W:
        return e172::ScancodeW;
    case SDL_SCANCODE_X:
        return e172::ScancodeX;
    case SDL_SCANCODE_Y:
        return e172::ScancodeY;
    case SDL_SCANCODE_Z:
        return e172::ScancodeZ;
    case SDL_SCANCODE_1:
        return e172::Scancode1;
    case SDL_SCANCODE_2:
        return e172::Scancode2;
    case SDL_SCANCODE_3:
        return e172::Scancode3;
    case SDL_SCANCODE_4:
        return e172::Scancode4;
    case SDL_SCANCODE_5:
        return e172::Scancode5;
    case SDL_SCANCODE_6:
        return e172::Scancode6;
    case SDL_SCANCODE_7:
        return e172::Scancode7;
    case SDL_SCANCODE_8:
        return e172::Scancode8;
    case SDL_SCANCODE_9:
        return e172::Scancode9;
    case SDL_SCANCODE_0:
        return e172::Scancode0;
    case SDL_SCANCODE_RETURN:
        return e172::ScancodeReturn;
    case SDL_SCANCODE_ESCAPE:
        return e172::ScancodeEscape;
    case SDL_SCANCODE_BACKSPACE:
        return e172::ScancodeBackSpace;
    case SDL_SCANCODE_TAB:
        return e172::ScancodeTab;
    case SDL_SCANCODE_SPACE:
        return e172::ScancodeSpace;
    case SDL_SCANCODE_MINUS:
        return e172::ScancodeMinus;
    case SDL_SCANCODE_EQUALS:
        return e172::ScancodeEquals;
    case SDL_SCANCODE_LEFTBRACKET:
        return e172::ScancodeLeftBracket;
    case SDL_SCANCODE_RIGHTBRACKET:
        return e172::ScancodeRightBracket;
    case SDL_SCANCODE_BACKSLASH:
        return e172::ScancodeBackslash;
    case SDL_SCANCODE_NONUSHASH:
        return e172::ScancodeNonUSHash;
    case SDL_SCANCODE_SEMICOLON:
        return e172::ScancodeSemicolon;
    case SDL_SCANCODE_APOSTROPHE:
        return e172::ScancodeApostrophe;
    case SDL_SCANCODE_GRAVE:
        return e172::ScancodeGrave;
    case SDL_SCANCODE_COMMA:
        return e172::ScancodeComma;
    case SDL_SCANCODE_PERIOD:
        return e172::ScancodePeriod;
    case SDL_SCANCODE_SLASH:
        return e172::ScancodeSlash;
    case SDL_SCANCODE_CAPSLOCK:
        return e172::ScancodeCapsLock;
    case SDL_SCANCODE_F1:
        return e172::ScancodeF1;
    case SDL_SCANCODE_F2:
        return e172::ScancodeF2;
    case SDL_SCANCODE_F3:
        return e172::ScancodeF3;
    case SDL_SCANCODE_F4:
        return e172::ScancodeF4;
    case SDL_SCANCODE_F5:
        return e172::ScancodeF5;
    case SDL_SCANCODE_F6:
        return e172::ScancodeF6;
    case SDL_SCANCODE_F7:
        return e172::ScancodeF7;
    case SDL_SCANCODE_F8:
        return e172::ScancodeF8;
    case SDL_SCANCODE_F9:
        return e172::ScancodeF9;
    case SDL_SCANCODE_F10:
        return e172::ScancodeF10;
    case SDL_SCANCODE_F11:
        return e172::ScancodeF11;
    case SDL_SCANCODE_F12:
        return e172::ScancodeF12;
    case SDL_SCANCODE_PRINTSCREEN:
        return e172::ScancodePrintScreen;
    case SDL_SCANCODE_SCROLLLOCK:
        return e172::ScancodeScrollLock;
    case SDL_SCANCODE_PAUSE:
        return e172::ScancodePause;
    case SDL_SCANCODE_INSERT:
        return e172::ScancodeInsert;
    case SDL_SCANCODE_HOME:
        return e172::ScancodeHome;
    case SDL_SCANCODE_PAGEUP:
        return e172::ScancodePageUp;
    case SDL_SCANCODE_DELETE:
        return e172::ScancodeDelete;
    case SDL_SCANCODE_END:
        return e172::ScancodeEnd;
    case SDL_SCANCODE_PAGEDOWN:
        return e172::ScancodePageDown;
    case SDL_SCANCODE_RIGHT:
        return e172::ScancodeRight;
    case SDL_SCANCODE_LEFT:
        return e172::ScancodeLeft;
    case SDL_SCANCODE_DOWN:
        return e172::ScancodeDown;
    case SDL_SCANCODE_UP:
        return e172::ScancodeUp;
    case SDL_SCANCODE_NUMLOCKCLEAR:
        return e172::ScancodeNumLockClear;
    case SDL_SCANCODE_KP_DIVIDE:
        return e172::ScancodeKpDivide;
    case SDL_SCANCODE_KP_MULTIPLY:
        return e172::ScancodeKpMultiply;
    case SDL_SCANCODE_KP_MINUS:
        return e172::ScancodeKpMinus;
    case SDL_SCANCODE_KP_PLUS:
        return e172::ScancodeKpPlus;
    case SDL_SCANCODE_KP_ENTER:
        return e172::ScancodeKpEnter;
    case SDL_SCANCODE_KP_1:
        return e172::ScancodeKp1;
    case SDL_SCANCODE_KP_2:
        return e172::ScancodeKp2;
    case SDL_SCANCODE_KP_3:
        return e172::ScancodeKp3;
    case SDL_SCANCODE_KP_4:
        return e172::ScancodeKp4;
    case SDL_SCANCODE_KP_5:
        return e172::ScancodeKp5;
    case SDL_SCANCODE_KP_6:
        return e172::ScancodeKp6;
    case SDL_SCANCODE_KP_7:
        return e172::ScancodeKp7;
    case SDL_SCANCODE_KP_8:
        return e172::ScancodeKp8;
    case SDL_SCANCODE_KP_9:
        return e172::ScancodeKp9;
    case SDL_SCANCODE_KP_0:
        return e172::ScancodeKp0;
    case SDL_SCANCODE_KP_PERIOD:
        return e172::ScancodeKpPeriod;
    case SDL_SCANCODE_NONUSBACKSLASH:
        return e172::ScancodeNonUSBackSlash;
    case SDL_SCANCODE_APPLICATION:
        return e172::ScancodeApplication;
    case SDL_SCANCODE_POWER:
        return e172::ScancodePower;
    case SDL_SCANCODE_KP_EQUALS:
        return e172::ScancodeEquals;
    case SDL_SCANCODE_F13:
        return e172::ScancodeF13;
    case SDL_SCANCODE_F14:
        return e172::ScancodeF14;
    case SDL_SCANCODE_F15:
        return e172::ScancodeF15;
    case SDL_SCANCODE_F16:
        return e172::ScancodeF16;
    case SDL_SCANCODE_F17:
        return e172::ScancodeF17;
    case SDL_SCANCODE_F18:
        return e172::ScancodeF18;
    case SDL_SCANCODE_F19:
        return e172::ScancodeF19;
    case SDL_SCANCODE_F20:
        return e172::ScancodeF20;
    case SDL_SCANCODE_F21:
        return e172::ScancodeF21;
    case SDL_SCANCODE_F22:
        return e172::ScancodeF22;
    case SDL_SCANCODE_F23:
        return e172::ScancodeF23;
    case SDL_SCANCODE_F24:
        return e172::ScancodeF24;
    case SDL_SCANCODE_EXECUTE:
        return e172::ScancodeExecute;
    case SDL_SCANCODE_HELP:
        return e172::ScancodeHelp;
    case SDL_SCANCODE_MENU:
        return e172::ScancodeMenu;
    case SDL_SCANCODE_SELECT:
        return e172::ScancodeSelect;
    case SDL_SCANCODE_STOP:
        return e172::ScancodeStop;
    case SDL_SCANCODE_AGAIN:
        return e172::ScancodeAgain;
    case SDL_SCANCODE_UNDO:
        return e172::ScancodeUndo;
    case SDL_SCANCODE_CUT:
        return e172::ScancodeCut;
    case SDL_SCANCODE_COPY:
        return e172::ScancodeCopy;
    case SDL_SCANCODE_PASTE:
        return e172::ScancodePaste;
    case SDL_SCANCODE_FIND:
        return e172::ScancodeFind;
    case SDL_SCANCODE_MUTE:
        return e172::ScancodeMute;
    case SDL_SCANCODE_VOLUMEUP:
        return e172::ScancodeVolumeUp;
    case SDL_SCANCODE_VOLUMEDOWN:
        return e172::ScancodeVolumeDown;
    case SDL_SCANCODE_KP_COMMA:
        return e172::ScancodeKPComma;
    case SDL_SCANCODE_KP_EQUALSAS400:
        return e172::ScancodeKPEqualSas400;
    case SDL_SCANCODE_INTERNATIONAL1:
        return e172::ScancodeInternational1;
    case SDL_SCANCODE_INTERNATIONAL2:
        return e172::ScancodeInternational2;
    case SDL_SCANCODE_INTERNATIONAL3:
        return e172::ScancodeInternational3;
    case SDL_SCANCODE_INTERNATIONAL4:
        return e172::ScancodeInternational4;
    case SDL_SCANCODE_INTERNATIONAL5:
        return e172::ScancodeInternational5;
    case SDL_SCANCODE_INTERNATIONAL6:
        return e172::ScancodeInternational6;
    case SDL_SCANCODE_INTERNATIONAL7:
        return e172::ScancodeInternational7;
    case SDL_SCANCODE_INTERNATIONAL8:
        return e172::ScancodeInternational8;
    case SDL_SCANCODE_INTERNATIONAL9:
        return e172::ScancodeInternational9;
    case SDL_SCANCODE_LANG1:
        return e172::ScancodeLang1;
    case SDL_SCANCODE_LANG2:
        return e172::ScancodeLang2;
    case SDL_SCANCODE_LANG3:
        return e172::ScancodeLang3;
    case SDL_SCANCODE_LANG4:
        return e172::ScancodeLang4;
    case SDL_SCANCODE_LANG5:
        return e172::ScancodeLang5;
    case SDL_SCANCODE_LANG6:
        return e172::ScancodeLang6;
    case SDL_SCANCODE_LANG7:
        return e172::ScancodeLang7;
    case SDL_SCANCODE_LANG8:
        return e172::ScancodeLang8;
    case SDL_SCANCODE_LANG9:
        return e172::ScancodeLang9;
    case SDL_SCANCODE_ALTERASE:
        return e172::ScancodeAltErase;
    case SDL_SCANCODE_SYSREQ:
        return e172::ScancodeSysReq;
    case SDL_SCANCODE_CANCEL:
        return e172::ScancodeCancel;
    case SDL_SCANCODE_CLEAR:
        return e172::ScancodeClear;
    case SDL_SCANCODE_PRIOR:
        return e172::ScancodePeriod;
    case SDL_SCANCODE_RETURN2:
        return e172::ScancodeReturn2;
    case SDL_SCANCODE_SEPARATOR:
        return e172::ScancodeSeparator;
    case SDL_SCANCODE_OUT:
        return e172::ScancodeOut;
    case SDL_SCANCODE_OPER:
        return e172::ScancodeOper;
    case SDL_SCANCODE_CLEARAGAIN:
        return e172::ScancodeClearAgain;
    case SDL_SCANCODE_CRSEL:
        return e172::ScancodeCrsel;
    case SDL_SCANCODE_EXSEL:
        return e172::ScancodeExsel;
    case SDL_SCANCODE_KP_00:
        return e172::ScancodeKP00;
    case SDL_SCANCODE_KP_000:
        return e172::ScancodeKP000;
    case SDL_SCANCODE_THOUSANDSSEPARATOR:
        return e172::ScancodeThousandsSeparator;
    case SDL_SCANCODE_DECIMALSEPARATOR:
        return e172::ScancodeDecimalSeparator;
    case SDL_SCANCODE_CURRENCYUNIT:
        return e172::ScancodeCurrencyUnit;
    case SDL_SCANCODE_CURRENCYSUBUNIT:
        return e172::ScancodeCurrencySubunit;
    case SDL_SCANCODE_KP_LEFTPAREN:
        return e172::ScancodeKpLeftParen;
    case SDL_SCANCODE_KP_RIGHTPAREN:
        return e172::ScancodeKpRightParen;
    case SDL_SCANCODE_KP_LEFTBRACE:
        return e172::ScancodeKpLeftBrace;
    case SDL_SCANCODE_KP_RIGHTBRACE:
        return e172::ScancodeKpRightBrace;
    case SDL_SCANCODE_KP_TAB:
        return e172::ScancodeKpTab;
    case SDL_SCANCODE_KP_BACKSPACE:
        return e172::ScancodeKpBackspace;
    case SDL_SCANCODE_KP_A:
        return e172::ScancodeKpA;
    case SDL_SCANCODE_KP_B:
        return e172::ScancodeKpB;
    case SDL_SCANCODE_KP_C:
        return e172::ScancodeKpC;
    case SDL_SCANCODE_KP_D:
        return e172::ScancodeKpD;
    case SDL_SCANCODE_KP_E:
        return e172::ScancodeKpE;
    case SDL_SCANCODE_KP_F:
        return e172::ScancodeKpE;
    case SDL_SCANCODE_KP_XOR:
        return e172::ScancodeKpXor;
    case SDL_SCANCODE_KP_POWER:
        return e172::ScancodeKpPower;
    case SDL_SCANCODE_KP_PERCENT:
        return e172::ScancodeKpPercent;
    case SDL_SCANCODE_KP_LESS:
        return e172::ScancodeKpLess;
    case SDL_SCANCODE_KP_GREATER:
        return e172::ScancodeKpGreater;
    case SDL_SCANCODE_KP_AMPERSAND:
        return e172::ScancodeKpAmpersand;
    case SDL_SCANCODE_KP_DBLAMPERSAND:
        return e172::ScancodeKpDblAmpersand;
    case SDL_SCANCODE_KP_VERTICALBAR:
        return e172::ScancodeKpVerticalBar;
    case SDL_SCANCODE_KP_DBLVERTICALBAR:
        return e172::ScancodeKpDblVerticalBar;
    case SDL_SCANCODE_KP_COLON:
        return e172::ScancodeKpColon;
    case SDL_SCANCODE_KP_HASH:
        return e172::ScancodeKpHash;
    case SDL_SCANCODE_KP_SPACE:
        return e172::ScancodeKpSpace;
    case SDL_SCANCODE_KP_AT:
        return e172::ScancodeKpAt;
    case SDL_SCANCODE_KP_EXCLAM:
        return e172::ScancodeKpExclam;
    case SDL_SCANCODE_KP_MEMSTORE:
        return e172::ScancodeKpMemStore;
    case SDL_SCANCODE_KP_MEMRECALL:
        return e172::ScancodeKpMemRecall;
    case SDL_SCANCODE_KP_MEMCLEAR:
        return e172::ScancodeKpMemClear;
    case SDL_SCANCODE_KP_MEMADD:
        return e172::ScancodeKpMemAdd;
    case SDL_SCANCODE_KP_MEMSUBTRACT:
        return e172::ScancodeKpMemSubtract;
    case SDL_SCANCODE_KP_MEMMULTIPLY:
        return e172::ScancodeKpMemMultiply;
    case SDL_SCANCODE_KP_MEMDIVIDE:
        return e172::ScancodeKpMemDivide;
    case SDL_SCANCODE_KP_PLUSMINUS:
        return e172::ScancodeKpPlusMinus;
    case SDL_SCANCODE_KP_CLEAR:
        return e172::ScancodeKpClear;
    case SDL_SCANCODE_KP_CLEARENTRY:
        return e172::ScancodeKpClearEntry;
    case SDL_SCANCODE_KP_BINARY:
        return e172::ScancodeKpBinary;
    case SDL_SCANCODE_KP_OCTAL:
        return e172::ScancodeKpOctal;
    case SDL_SCANCODE_KP_DECIMAL:
        return e172::ScancodeKpDecimal;
    case SDL_SCANCODE_KP_HEXADECIMAL:
        return e172::ScancodeKpHexadecimal;
    case SDL_SCANCODE_LCTRL:
        return e172::ScancodeLCtrl;
    case SDL_SCANCODE_LSHIFT:
        return e172::ScancodeLShift;
    case SDL_SCANCODE_LALT:
        return e172::ScancodeLAlt;
    case SDL_SCANCODE_LGUI:
        return e172::ScancodeLGui;
    case SDL_SCANCODE_RCTRL:
        return e172::ScancodeRCtrl;
    case SDL_SCANCODE_RSHIFT:
        return e172::ScancodeRShift;
    case SDL_SCANCODE_RALT:
        return e172::ScancodeRAlt;
    case SDL_SCANCODE_RGUI:
        return e172::ScancodeRGui;
    case SDL_SCANCODE_MODE:
        return e172::ScancodeMode;
    case SDL_SCANCODE_AUDIONEXT:
        return e172::ScancodeAudioNext;
    case SDL_SCANCODE_AUDIOPREV:
        return e172::ScancodeAudioPrev;
    case SDL_SCANCODE_AUDIOSTOP:
        return e172::ScancodeAudioStop;
    case SDL_SCANCODE_AUDIOPLAY:
        return e172::ScancodeAudioPlay;
    case SDL_SCANCODE_AUDIOMUTE:
        return e172::ScancodeAudioMute;
    case SDL_SCANCODE_MEDIASELECT:
        return e172::ScancodeMediaSelect;
    case SDL_SCANCODE_WWW:
        return e172::ScancodeWWW;
    case SDL_SCANCODE_MAIL:
        return e172::ScancodeMail;
    case SDL_SCANCODE_CALCULATOR:
        return e172::ScancodeCalculator;
    case SDL_SCANCODE_COMPUTER:
        return e172::ScancodeComputer;
    case SDL_SCANCODE_AC_SEARCH:
        return e172::ScancodeAcSearch;
    case SDL_SCANCODE_AC_HOME:
        return e172::ScancodeAcHome;
    case SDL_SCANCODE_AC_BACK:
        return e172::ScancodeAcBack;
    case SDL_SCANCODE_AC_FORWARD:
        return e172::ScancodeAcForward;
    case SDL_SCANCODE_AC_STOP:
        return e172::ScancodeAcStop;
    case SDL_SCANCODE_AC_REFRESH:
        return e172::ScancodeAcRefresh;
    case SDL_SCANCODE_AC_BOOKMARKS:
        return e172::ScancodeAcBookmarks;
    case SDL_SCANCODE_BRIGHTNESSDOWN:
        return e172::ScancodeBrightnessDown;
    case SDL_SCANCODE_BRIGHTNESSUP:
        return e172::ScancodeBrightnessUp;
    case SDL_SCANCODE_DISPLAYSWITCH:
        return e172::ScancodeDisplaySwitch;
    case SDL_SCANCODE_KBDILLUMTOGGLE:
        return e172::ScancodeKbDillumToggle;
    case SDL_SCANCODE_KBDILLUMDOWN:
        return e172::ScancodeKbDillumDown;
    case SDL_SCANCODE_KBDILLUMUP:
        return e172::ScancodeKbDillumUp;
    case SDL_SCANCODE_EJECT:
        return e172::ScancodeEject;
    case SDL_SCANCODE_SLEEP:
        return e172::ScancodeSleep;
    case SDL_SCANCODE_APP1:
        return e172::ScancodeApp1;
    case SDL_SCANCODE_APP2:
        return e172::ScancodeApp2;
    case SDL_SCANCODE_AUDIOREWIND:
        return e172::ScancodeAudioRewind;
    case SDL_SCANCODE_AUDIOFASTFORWARD:
        return e172::ScancodeAudioFastForward;
    case SDL_SCANCODE_SOFTLEFT:
        return e172::ScancodeSoftLeft;
    case SDL_SCANCODE_SOFTRIGHT:
        return e172::ScancodeSoftRight;
    case SDL_SCANCODE_CALL:
        return e172::ScancodeCall;
    case SDL_SCANCODE_ENDCALL:
        return e172::ScancodeEndCall;
    case SDL_NUM_SCANCODES:
        return e172::ScancodesCount;
    }
    return e172::ScancodeUnknown;
}
} // namespace

std::optional<e172::Event> SDLEventProvider::pullEvent()
{
    SDL_Event event;
    if (SDL_PollEvent(&event)) {
        if (event.type == SDL_KEYDOWN) {
            return e172::Event::keyDown(scancodeFromSDL(event.key.keysym.scancode));
        } else if (event.type == SDL_KEYUP) {
            return e172::Event::keyUp(scancodeFromSDL(event.key.keysym.scancode));
        } else if (event.type == SDL_MOUSEMOTION) {
            return e172::Event::mouseMotion(e172::Event::Pos(event.motion.x, event.motion.y));
        } else if (event.type == SDL_QUIT) {
            return e172::Event::quit();
        }
    }
    return std::nullopt;
}
